### ISSUE TITLE
日志转sql支持mybatis-plus吗.  

### ISSUE THREAD

**Issue by HengCC** [gejun123456/MyBatisCodeHelper-Pro#1002]
在集成mybatis之前. 打开监控sql的开关. 是可以监控到执行的sql的.  但是集成了mybatis-plus后这个功能就失效了.  有没有办法能支持呢

**Comment by HengCC** [comment]
<img width="335" alt="image" src="https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/6167532/d9263435-05a5-4fff-aaed-1d0d5933a1ff">

**Comment by gejun123456** [comment]
支持的，可以把日志发我下看看

**Comment by HengCC** [comment]
> 支持的，可以把日志发我下看看

谢谢回复. 不过我不太清楚如何查看插件日志. 在集成mybatis-plus之前.  上面截图中会自动捕获系统运行过程中产生的sql并且做去重和带参数的打印转换. 集成之后就不在显示了.  我猜测是数据源的配置有变化. 目前是通过mybatis-plus提供的方案集成了p6spy来做的sql打印. [mybatis p6spy](https://baomidou.com/guides/p6spy/)
```
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
    driver-class-name: com.mysql.cj.jdbc.Driver
```
