### ISSUE TITLE
kotlin 中 alias 跳转失效

### ISSUE THREAD

**Issue by GoldSubmarine** [gejun123456/MyBatisCodeHelper-Pro#679]
![image](https://user-images.githubusercontent.com/22909744/110270778-8d5df600-8001-11eb-9a01-1de69736b466.png)

我的项目使用的是 kotlin 语言，使用的 mybatis-plus，并进行了如下配置

```yml
mybatis-plus:
  mapper-locations: classpath*:/com/javahub/**/*.xml
  type-aliases-package: com.javahub.lagoon.**.domain
```

我确信 alias 配置没有问题，因为代码运行起来后，能正确的执行映射，并且我尝试了一下 MybatisX 这个插件，它可以正确调转

在 java 项目中没有问题，但是 kotlin 不行，我想这是一个 bug
